spring:
  profiles:
    active: local

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false


server:
  port: 8080
  servlet:
    context-path: /dev