spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlinecv
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      timeout: 3
      database:
          db0: 0
          db1: 1
      lettuce:
        pool:
          max-active: 100
          max-idle: 10
          min-idle: 0





