spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.140.143.119:17546/onlinecv
    username: root
    password: arthur7evans
  data:
    redis:
      host: 8.140.143.119
      port: 6379
      password: 123456
      timeout: 3
      database:
        db0: 0
        db1: 1
      lettuce:
        pool:
          max-active: 100
          max-idle: 10
          min-idle: 0

